name: Build and publish a Docker image to ghcr.io
on:
  push:
    branches:
      - main

jobs:
  docker_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: ${{ github.actor }}/${{ github.repository }}@main
        with:
          image_name: ${{ github.repository }}  # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}
